In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('/Users/devammpatel/Desktop/Supervised ML Project on Airbnb Dataset/Dataset/Airbnb_Open_Data.csv')
df.head()

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1676522731.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/devammpatel/Desktop/Supervised ML Project on Airbnb Dataset/Dataset/Airbnb_Open_Data.csv')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 46.7+ MB

In [4]:
df.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

There are lots of missing values, we will have to clean the dataset. Wherever we can, we will deleted the data row burt somewhere we will have to input some data by different methods.

In [5]:
df.shape

(102599, 26)

In [6]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

First of all lets straightaway drop the rows with name value as null, as we can not input any random value for it.

In [7]:
df.dropna(subset='NAME', inplace=True)

Similarly dropping rows with unknown host name

In [9]:
df.dropna(subset='host name', inplace=True)

In [10]:
df.isnull().sum()

id                                     0
NAME                                   0
host id                                0
host_identity_verified               276
host name                              0
neighbourhood group                   26
neighbourhood                         16
lat                                    8
long                                   8
country                              526
country code                         122
instant_bookable                      96
cancellation_policy                   70
room type                              0
Construction year                    200
price                                239
service fee                          268
minimum nights                       403
number of reviews                    182
last review                        15777
reviews per month                  15763
review rate number                   314
calculated host listings count       318
availability 365                     420
house_rules                        51867
license                           101947
dtype: int64

In [20]:
df['country'].unique()

<ArrowStringArray>
['United States', nan]
Length: 2, dtype: str

In [19]:
df['country code'].unique()

<ArrowStringArray>
['US', nan]
Length: 2, dtype: str

As both country and country code represents United states only, lets just drop 'country' and fill the missing values in country code with US.

In [21]:
df.drop(['country'], axis=1, inplace=True)

In [42]:
#Replace 'nan' with 'US' in 'country code' where it is null
df['country code'] = df['country code'].where(df['country code'].notnull(), 'US', inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/3686540692.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['country code'] = df['country code'].where(df['country code'].notnull(), 'US', inplace=True)

In [43]:
df['country code'].unique()

<ArrowStringArray>
['US']
Length: 1, dtype: str

In [46]:
df[df.duplicated()]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country code,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102058,35506831,Master Bedroom with private Bathroom & Balcony,55110690425,unconfirmed,UZeyir,Queens,Maspeth,40.74056,-73.90635,US,...,$141,1.0,1.0,11/14/2021,0.27,3.0,1.0,339.0,NaN,NaN
102059,35507383,Cozy 2 br in sunny Fort Greene apt,80193772189,verified,Sally,Brooklyn,Fort Greene,40.68701,-73.97555,US,...,$130,3.0,38.0,11/13/2021,0.27,3.0,1.0,0.0,NaN,NaN
102060,35507935,Duplex w/ Terrace @ Box House Hotel,72991962259,verified,The Box House Hotel,Brooklyn,Greenpoint,40.73756,-73.95350,US,...,$181,3.0,10.0,11/13/2021,0.08,3.0,30.0,32.0,NaN,NaN
102061,35508488,"Cozy, clean Greenpoint room with yard access",74975156081,verified,Dawn,Brooklyn,Greenpoint,40.72516,-73.95004,US,...,$118,30.0,38.0,11/13/2021,0.34,5.0,2.0,324.0,NaN,NaN
102062,35509040,2BR XL Loft: Cleaning CDC guidelines implemented,85844415221,unconfirmed,Vida,Brooklyn,Greenpoint,40.72732,-73.94185,US,...,$71,30.0,13.0,11/13/2021,0.14,4.0,28.0,336.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,US,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,US,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,US,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,US,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,US,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

Lets also drop this duplicates

In [47]:
#Droping duplicates
df.drop_duplicates(inplace=True)

In [48]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license]
Index: []

[0 rows x 25 columns]

In [54]:
df['host_identity_verified'].value_counts()

host_identity_verified
unconfirmed    50634
verified       50500
Name: count, dtype: int64

Lets replace nan values in 'host_identity_verified' with equal number of both verified and unverified as this both is already in almost equal numbers

In [56]:
#Lets replace 'nan' values in 'host_identity_verified' with equal number of 'unconfirmed' and 'confirmed' entries to maintain the balance in the dataset
num_nan = df['host_identity_verified'].isnull().sum()
num_unconfirmed = num_nan // 2
num_confirmed = num_nan - num_unconfirmed
df.loc[df['host_identity_verified'].isnull(), 'host_identity_verified'] = ['unconfirmed'] * num_unconfirmed + ['confirmed'] * num_confirmed

Replace 'confirmed' with 'verified'because 'confirmed' and 'verified' are essentially the same in the context of host identity verification, and we want to maintain consistency in our dataset.

In [ ]:
df['host_identity_verified'] = df['host_identity_verified'].replace('confirmed', 'verified')

In [59]:
df['host_identity_verified'].value_counts()

host_identity_verified
unconfirmed    50772
verified       50638
Name: count, dtype: int64

In [102]:
df.isnull().sum()

id                                    0
NAME                                  0
host id                               0
host_identity_verified                0
host name                             0
neighbourhood group                   0
neighbourhood                         0
lat                                   8
long                                  8
country code                          0
instant_bookable                     93
cancellation_policy                  67
room type                             0
Construction year                   197
price                               237
service fee                         268
minimum nights                      392
number of reviews                   182
last review                       15713
reviews per month                 15701
review rate number                  305
calculated host listings count      318
availability 365                    409
house_rules                           0
license                               0
dtype: int64

Dropping columns with null values in 'neighbourhood group' & 'neighbourhood' as their is as such no replacement or dummy value we can input

In [101]:
# Lets drop rows that have 'nan' values in  'neighbourhood group' and 'neighbourhood' columns as they are important for our analysis and the number of such rows is very less
df.dropna(subset=['neighbourhood group', 'neighbourhood'], inplace=True)

## Now let's clean rest of the data in one go

In [97]:
# Lets replace 'nan' values in house rules with 'No rules' to maintain the balance in the dataset
df['house_rules'] = df['house_rules'].where(df['house_rules'].notnull(), 'No rules', inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/4110933978.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['house_rules'] = df['house_rules'].where(df['house_rules'].notnull(), 'No rules', inplace=True)

In [98]:
#lets replace 'nan' values in license with 'No license' to maintain the balance in the dataset
df['license'] = df['license'].where(df['license'].notnull(), 'No license', inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/3597274254.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['license'] = df['license'].where(df['license'].notnull(), 'No license', inplace=True)

In [103]:
#lets replace 'nan' values in 'Construction year' with the median value of the column
median_construction_year = df['Construction year'].median()
df['Construction year'] = df['Construction year'].where(df['Construction year'].notnull(), median_construction_year, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/4177484970.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Construction year'] = df['Construction year'].where(df['Construction year'].notnull(), median_construction_year, inplace=True)

In [104]:
#lets replace 'nan' values in 'lat' and 'long' with the average value of the respective columns
mean_lat = df['lat'].mean()
mean_long = df['long'].mean()
df['lat'] = df['lat'].where(df['lat'].notnull(), mean_lat, inplace=True)
df['long'] = df['long'].where(df['long'].notnull(), mean_long, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1240807701.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['lat'] = df['lat'].where(df['lat'].notnull(), mean_lat, inplace=True)
/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1240807701.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['long'] = df['long'].where(df['long'].notnull(), mean_long, inplace=True)

In [105]:
#lets replace 'nan' values in 'instant_bookable' with randomly assigned 'True' and 'False' values to maintain the balance in the dataset
num_nan_instant_bookable = df['instant_bookable'].isnull().sum()
num_true = num_nan_instant_bookable // 2
num_false = num_nan_instant_bookable - num_true
df.loc[df['instant_bookable'].isnull(), 'instant_bookable'] = [True] * num_true + [False] * num_false

In [106]:
#lets replace 'nan' values in 'cancellation_policy' with randomly assigned 'flexible', 'moderate' and 'strict' values to maintain the balance in the dataset
num_nan_cancellation_policy = df['cancellation_policy'].isnull().sum()
df.loc[df['cancellation_policy'].isnull(), 'cancellation_policy'] = np.random.choice(['flexible', 'moderate', 'strict'], size=num_nan_cancellation_policy)

In [110]:
df['price'].unique()

<ArrowStringArray>
[  '$966 ',   '$142 ',   '$620 ',   '$204 ',   '$577 ',    '$71 ', '$1,060 ',
 '$1,018 ',   '$291 ',   '$319 ',
 ...
 '$1,169 ',   '$404 ',   '$390 ',   '$992 ',   '$743 ',   '$168 ',   '$918 ',
 '$1,184 ',   '$905 ',   '$309 ']
Length: 1152, dtype: str

In [109]:
#lets replace 'nan' values in 'price' with the average value of the column
mean_price = df['price'].mean()
df['price'] = df['price'].where(df['price'].notnull(), mean_price, inplace=True)

TypeError: Cannot perform reduction 'mean' with string dtype

In [111]:
#lets first covert the 'price' column to numeric values by removing the '$' sign and then replacing 'nan' values in 'price' with the average value of the column
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)
mean_price = df['price'].mean()
df['price'] = df['price'].where(df['price'].notnull(), mean_price, inplace=True)

<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/388373987.py:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)
/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/388373987.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['price'] = df['price'].where(df['price'].notnull(), mean_price, inplace=True)

In [115]:
df['service fee'].unique()

<ArrowStringArray>
['$193 ',  '$28 ', '$124 ',  '$41 ', '$115 ',  '$14 ', '$212 ', '$204 ',
  '$58 ',  '$64 ',
 ...
 '$173 ',  '$60 ',  '$80 ', '$214 ', '$150 ',  '$78 ', '$230 ', '$112 ',
 '$200 ',  '$53 ']
Length: 232, dtype: str

In [116]:
#lets first convert the 'service fee' column to numeric values and then replace 'nan' values with the average value of the column
df['service fee'] = df['service fee'].replace('[\$,]', '', regex=True).astype(float)
mean_service_fee = df['service fee'].mean()
df['service fee'] = df['service fee'].where(df['service fee'].notnull(), mean_service_fee, inplace=True)

<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/4234596666.py:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df['service fee'] = df['service fee'].replace('[\$,]', '', regex=True).astype(float)
/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/4234596666.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['service fee'] = df['service fee'].where(df['service fee'].notnull(), mean_service_fee, inplace=True)

In [118]:
#lets replace 'nan' values in 'reviews per month' with the average value of the column
mean_reviews_per_month = df['reviews per month'].mean()
df['reviews per month'] = df['reviews per month'].where(df['reviews per month'].notnull(), mean_reviews_per_month, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/3281588977.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['reviews per month'] = df['reviews per month'].where(df['reviews per month'].notnull(), mean_reviews_per_month, inplace=True)

In [119]:
#lets replace 'nan' values in 'review rate number' with the average value of the column
mean_review_rate_number = df['review rate number'].mean()
df['review rate number'] = df['review rate number'].where(df['review rate number'].notnull(), mean_review_rate_number, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1289474862.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['review rate number'] = df['review rate number'].where(df['review rate number'].notnull(), mean_review_rate_number, inplace=True)

In [120]:
#lets replace 'nan' values in 'calculated host listings count' with the mode value of the column
mode_calculated_host_listings_count = df['calculated host listings count'].mode()[0]
df['calculated host listings count'] = df['calculated host listings count'].where(df['calculated host listings count'].notnull(), mode_calculated_host_listings_count, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/2449383028.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['calculated host listings count'] = df['calculated host listings count'].where(df['calculated host listings count'].notnull(), mode_calculated_host_listings_count, inplace=True)

In [121]:
# Lets replace 'nan' values in 'last review' with the most recent date in the column to maintain the balance in the dataset
most_recent_date = df['last review'].max()
df['last review'] = df['last review'].where(df['last review'].notnull(), most_recent_date, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/3179289514.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['last review'] = df['last review'].where(df['last review'].notnull(), most_recent_date, inplace=True)

In [128]:
# number of reviews column has some outliers. Lets replace those outliers with the median value of the column to maintain the balance in the dataset
median_number_of_reviews = df['number of reviews'].median()
df['number of reviews'] = df['number of reviews'].where(df['number of reviews'] <= 100, median_number_of_reviews, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1011749314.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['number of reviews'] = df['number of reviews'].where(df['number of reviews'] <= 100, median_number_of_reviews, inplace=True)

In [147]:
# availability 365 column has some outliers. Lets replace those outliers with the median value of the column to maintain the balance in the dataset
median_availability_365 = df['availability 365'].median()
df['availability 365'] = df['availability 365'].where(df['availability 365'] <= 200, median_availability_365, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/478694125.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['availability 365'] = df['availability 365'].where(df['availability 365'] <= 200, median_availability_365, inplace=True)

In [134]:
# Minimum nights column has some outliers. Lets replace those outliers with the median value of the column to maintain the balance in the dataset
median_minimum_nights = df['minimum nights'].median()
df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] <= 30, median_minimum_nights, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1619812330.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] <= 30, median_minimum_nights, inplace=True)

In [138]:
df['minimum nights'].astype(int)

0         10
1         30
2          3
4         10
5          3
          ..
102053     7
102054     1
102055     2
102056     2
102057     4
Name: minimum nights, Length: 101368, dtype: int64

In [140]:
df['minimum nights'].value_counts()

minimum nights
 1.0       25108
 2.0       23348
 3.0       18000
 30.0      11478
 4.0        6559
 5.0        5991
 7.0        3993
 6.0        1513
 14.0       1062
 10.0        924
 15.0        587
 29.0        553
 20.0        436
 28.0        430
 21.0        250
 8.0         240
 12.0        170
 9.0         157
 25.0        153
 13.0        105
 11.0         55
 18.0         48
 27.0         40
 16.0         33
 26.0         27
 17.0         23
 24.0         20
 23.0         18
 19.0         17
 22.0         17
-10.0          4
-5.0           1
-1.0           1
-12.0          1
-2.0           1
-3.0           1
-1223.0        1
-365.0         1
-200.0         1
-125.0         1
Name: count, dtype: int64

In [141]:
# Still minimum nights column has some outliers. Lets replace those outliers with the median value of the column to maintain the balance in the dataset
median_minimum_nights = df['minimum nights'].median()
df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] <= 14, median_minimum_nights, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1370351253.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] <= 14, median_minimum_nights, inplace=True)

In [143]:
df['minimum nights'].value_counts()

minimum nights
 3.0       32130
 1.0       25108
 2.0       23348
 4.0        6559
 5.0        5991
 7.0        3993
 6.0        1513
 14.0       1062
 10.0        924
 8.0         240
 12.0        170
 9.0         157
 13.0        105
 11.0         55
-10.0          4
-5.0           1
-1.0           1
-12.0          1
-2.0           1
-3.0           1
-1223.0        1
-365.0         1
-200.0         1
-125.0         1
Name: count, dtype: int64

Why are minimum night column having negative values? Are those values correct or they are data entry errors? We need to investigate this further to understand the reason behind these negative values in minimum nights column.

In [144]:
# Replace negative values in 'minimum nights' column with the median value of the column to maintain the balance in the dataset
median_minimum_nights = df['minimum nights'].median()
df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] >= 0, median_minimum_nights, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1208797174.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['minimum nights'] = df['minimum nights'].where(df['minimum nights'] >= 0, median_minimum_nights, inplace=True)

In [146]:
df['minimum nights'].value_counts()

minimum nights
3.0     32143
1.0     25108
2.0     23348
4.0      6559
5.0      5991
7.0      3993
6.0      1513
14.0     1062
10.0      924
8.0       240
12.0      170
9.0       157
13.0      105
11.0       55
Name: count, dtype: int64

In [148]:
df.isnull().sum()

id                                0
NAME                              0
host id                           0
host_identity_verified            0
host name                         0
neighbourhood group               0
neighbourhood                     0
lat                               0
long                              0
country code                      0
instant_bookable                  0
cancellation_policy               0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
last review                       0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
house_rules                       0
license                           0
dtype: int64

## Finally the data is completely cleaned and without any null values

In [150]:
df['availability 365'].unique()

array([ 96., 180.,   1., 163.,  47.,  68., 100., 197., 193.,  54.,   9.,
       103., 172.,  56., 105., 169.,  76., 110.,  33.,  86., 152.,  26.,
        32.,  85.,  82.,  61., 189.,  83.,  34.,  35., 162., 173., 146.,
       113.,  58.,  13.,  62.,  92., -10.,  -2.,  16., 166.,  18., 130.,
        43., 190.,  52.,  70., 141.,  -1., 200., 144.,  19., 156., 138.,
       124., 137., 192.,  81.,  23.,  78., 188.,  66.,  80.,  12.,   0.,
        50., 118., 145.,  46., 101., 104., 135.,  87.,  42., 177., 179.,
        31.,  95., 154.,  -9.,  45., 176.,  53.,   5., 140., 107., 131.,
       117., 119., 155.,  84., 198., 143., 132., 114.,  77., 112.,  -4.,
       199.,  10.,  75., 182., 164.,  -6., 191.,  71.,  98., 159., 186.,
       187.,  88., 171., 129.,  30.,  97.,  -8.,  93.,  91., 150., 122.,
         7.,  29., 175.,  69.,  36., 149.,  39.,   3., 183.,   8.,  60.,
       153., 158.,  67., 109.,  -5., 167., 178.,  14.,  22.,  73.,  64.,
       181., 142.,  28., 174., 133.,  17.,  27., 106.,  41., 108., 168.,
       125.,  57., 139.,  65.,  25., 195.,  37.,  11., 116., 115., 134.,
         6., 194., 111., 196.,  15.,  79., 185.,  90.,   2.,   4., 160.,
        44., 126.,  38.,  55.,  72.,  21., 165.,  74., 147., 170.,  89.,
       128., 121.,  24.,  59., 123.,  -3.,  20.,  99.,  51., 184., 136.,
        49., 151., 127., 148.,  63.,  94., 161.,  40., 157., 102.,  48.,
       120.,  -7.])

In [151]:
# Replace negative values in 'availability 365' column with the median value of the column to maintain the balance in the dataset
median_availability_365 = df['availability 365'].median()
df['availability 365'] = df['availability 365'].where(df['availability 365'] >= 0, median_availability_365, inplace=True)

/var/folders/mq/0vb8lcg15nb96j2b87_3xdrh0000gn/T/ipykernel_21315/1437111155.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['availability 365'] = df['availability 365'].where(df['availability 365'] >= 0, median_availability_365, inplace=True)

In [152]:
df['availability 365'].value_counts()

availability 365
96.0     35001
0.0      23236
89.0       743
1.0        728
179.0      677
         ...
196.0       93
183.0       92
181.0       87
195.0       81
187.0       77
Name: count, Length: 201, dtype: int64

In [154]:
df.info()

<class 'pandas.DataFrame'>
Index: 101368 entries, 0 to 102057
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              101368 non-null  int64
 1   NAME                            101368 non-null  str
 2   host id                         101368 non-null  int64
 3   host_identity_verified          101368 non-null  str
 4   host name                       101368 non-null  str
 5   neighbourhood group             101368 non-null  str
 6   neighbourhood                   101368 non-null  str
 7   lat                             101368 non-null  float64
 8   long                            101368 non-null  float64
 9   country code                    101368 non-null  str
 10  instant_bookable                101368 non-null  object
 11  cancellation_policy             101368 non-null  str
 12  room type                       101368 non-null  str
 13  Construction year               101368 non-null  float64
 14  price                           101368 non-null  float64
 15  service fee                     101368 non-null  float64
 16  minimum nights                  101368 non-null  float64
 17  number of reviews               101368 non-null  float64
 18  last review                     101368 non-null  str
 19  reviews per month               101368 non-null  float64
 20  review rate number              101368 non-null  float64
 21  calculated host listings count  101368 non-null  float64
 22  availability 365                101368 non-null  float64
 23  house_rules                     101368 non-null  str
 24  license                         101368 non-null  str
dtypes: float64(11), int64(2), object(1), str(11)
memory usage: 45.4+ MB

In [155]:
df.describe()

,id,host id,lat,long,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.013680e+05,1.013680e+05,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000,101368.000000
mean,2.922075e+07,4.926099e+10,40.728077,-73.949662,2012.485844,625.356706,125.039110,2.889511,15.655641,1.376597,3.278569,7.928350,69.381097
std,1.626204e+07,2.853577e+10,0.055849,0.049476,5.759515,331.226180,66.227256,2.092381,21.986798,1.608609,1.283397,32.286849,54.601945
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,50.000000,10.000000,1.000000,0.000000,0.010000,1.000000,1.000000,0.000000
25%,1.509424e+07,2.459659e+10,40.688730,-73.982570,2008.000000,341.000000,68.000000,2.000000,1.000000,0.280000,2.000000,1.000000,4.000000
50%,2.924071e+07,4.912010e+10,40.722300,-73.954440,2012.000000,625.356706,125.000000,3.000000,7.000000,1.060000,3.000000,1.000000,96.000000
75%,4.328888e+07,7.399645e+10,40.762743,-73.932340,2017.000000,912.000000,182.000000,3.000000,20.000000,1.710000,4.000000,2.000000,96.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,14.000000,100.000000,90.000000,5.000000,332.000000,200.000000

#### We are now successfull in cleaning the data and along with that we have even removed unwanted enteries, duplicated rows and outliers.

In [162]:
df.shape

(101368, 25)

In [164]:
#Lets save the cleaned dataset to a new CSV file
df.to_csv('/Users/devammpatel/Desktop/Supervised ML Project on Airbnb Dataset/Dataset/Airbnb_Open_Data_Cleaned.csv', index=False)